# Generated by Django 4.0.6 on 2024-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date_created',
        ),
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
