# Generated by Django 4.0.6 on 2024-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_report_date_created_report_report_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_file',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
