# Generated by Django 4.0.6 on 2024-04-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_report_description_report_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
