# Generated by Django 5.0.3 on 2024-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_report_notes_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
