# Generated by Django 4.0.6 on 2024-04-10 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='reportDescription',
        ),
        migrations.AddField(
            model_name='report',
            name='crimeType',
            field=models.CharField(choices=[('Larceny/Theft', 'Larceny/Theft'), ('Vandalism', 'Vandalism'), ('Assault', 'Assault'), ('Harassing Phone Calls', 'Harassing Phone Calls'), ('Computer Harassment', 'Computer Harassment'), ('Narcotics/Drugs', 'Narcotics/Drugs')], default='Larceny/Theft', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='descriptionItems',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='discussion',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='report',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='timeOfIncident',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
